
Imports ZXing  'install zxing library by micheal jahn from nuget 
Imports System.Data.SqlClient

Public Class barcode_genFrm
    Dim con As New SqlClient.SqlConnection
    Dim cmd As New SqlClient.SqlCommand

    Dim cs As String = "Data Source=ANIRUDH;Initial Catalog=attastore;Integrated Security=True"  'connection string to connect with sql server
    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click

        autogenerated_barcode()
        generate_barcode()
        insert()
        save_to_computer()
        ' barcode_gen_txt.Text = ""

    End Sub
    Private Sub generate_barcode()
        Dim barwriter As New BarcodeWriter
        barwriter.Format = BarcodeFormat.CODE_128
        PictureBox1.Image = barwriter.Write(barcode_gen_txt.Text)
    End Sub
    Private Sub insert()
        Try
            con.ConnectionString = cs
            cmd.Connection = con
            con.Open()
            cmd.CommandText = "insert into barcode_generate(Barcode)values('" & barcode_gen_txt.Text & "')"
            cmd.ExecuteNonQuery()

            welcomemsg.ForeColor = System.Drawing.Color.DarkGreen
            welcomemsg.Text = "'" & barcode_gen_txt.Text & "' details saved successfully!"
            con.Close()
        Catch ex As Exception
            MsgBox("Data Inserted Failed because " & ex.Message)
            Me.Dispose()
        End Try

    End Sub
    Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
        Dim barreader As New BarcodeReader
        Dim res = barreader.Decode(CType(PictureBox1.Image, Bitmap))
        If res IsNot Nothing Then
            TextBox2.Text = res.Text
        End If
    End Sub
    Private Sub autogenerated_barcode()
        Try
            Dim curValue As Integer
            Dim result As String
            Using con As SqlConnection = New SqlConnection(cs)
                con.Open()
                Dim cmd = New SqlCommand("select Max(Barcode) from barcode_generate", con)
                result = cmd.ExecuteScalar().ToString()
                If String.IsNullOrEmpty(result) Then
                    result = "0000000000"
                End If

                result = result.Substring(3)
                Int32.TryParse(result, curValue)
                curValue = curValue + 1
                result = curValue.ToString("D10")
                barcode_gen_txt.Text = result
            End Using
        Catch ex As Exception
            MessageBox.Show("Failed:AutoIncrement of ServicesID" & ex.Message)
            Me.Dispose()
        End Try
    End Sub
    Private Sub save_to_computer()
        If PictureBox1.Image Is Nothing Then
            Return
        End If
        Dim saveFileDialog As SaveFileDialog = New SaveFileDialog()
        saveFileDialog.Filter = "PNG|*.png"
        If saveFileDialog.ShowDialog() = DialogResult.OK Then
            PictureBox1.Image.Save(saveFileDialog.FileName)
        End If
    End Sub

    Private Sub barcode_genFrm_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        autogenerated_barcode()
    End Sub

    Private Sub Button4_Click(sender As Object, e As EventArgs)
        Me.Close()
    End Sub

    Private Sub PictureBox2_Click(sender As Object, e As EventArgs) Handles PictureBox2.Click

        Dashboard_frm.Show()
        Me.Close()
    End Sub

    Private Sub PictureBox3_Click(sender As Object, e As EventArgs) Handles PictureBox3.Click
        Me.Close()
    End Sub
End Class